<?php
/**
 * Foodgo Gourmet Food Ordering Platform
 * Sample Configuration Template
 * 
 * NOTE: This file is automatically generated upon running install.php.
 * Do not manually expose database credentials to client-side code.
 */

if (!defined('FOODGO_ACCESS')) {
    define('FOODGO_ACCESS', true);
}

return [
    'app' => [
        'name'        => 'Foodgo',
        'url'         => 'http://localhost',
        'env'         => 'production', // 'production' or 'development'
        'debug'       => false,
        'secret'      => 'CHANGE_ME_TO_A_CRYPTOGRAPHICALLY_SECURE_RANDOM_KEY',
        'timezone'    => 'Asia/Kolkata',
        'currency'    => 'INR (₹)',
    ],
    'database' => [
        'host'        => 'localhost',
        'port'        => 3306,
        'database'    => 'foodgo_db',
        'username'    => 'foodgo_user',
        'password'    => 'secret_password',
        'charset'     => 'utf8mb4',
        'collation'   => 'utf8mb4_unicode_ci',
    ],
    'upload' => [
        'max_size_mb' => 15,
        'allowed_image_types' => ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
        'allowed_audio_types' => ['audio/webm', 'audio/mp4', 'audio/ogg', 'audio/wav', 'audio/mpeg'],
    ],
    'installed' => false,
];
